sentence = input('enter word\n')
sentence = sentence.lower()
v1 = sentence.count('a')
v2 = sentence.count('e')
v3 = sentence.count('i')
v4 = sentence.count('o')
v5 = sentence.count('u')
total = (v1+v2+v3+v4+v5)
print(total)

